### ISSUE TITLE
FBまとめ_優先順位記載（12月16日更新）

### ISSUE THREAD

**Issue by taiki0521** [INxST/st-portfolio#122]
@naoki-00-ito 
全ページの現段階のFBまとめましたので優先度高から随時ご対応いただければありがたいです！
（一旦こっちでできたやつからチェックつけてもらって、それをgitの各ページのFB箇所にも反映していくつもり）

○**優先度：高**

 ▼ローディングアニメーション

- [x]  LINEでも伝えた、SPで見た時に動画再生ボタンが出てしまうのはマストで無くしたいです。
その上で可能であればやっぱり毎回動画を再生させたいけど、重くて無理な場合は動画が入っている時と同じ見た目で静止画が入る
→ある程度時間がたってローディングすんだらそのまま動画が動き始める
という感じにしたいです！(issue)

 ▼共有パーツ・トップページ

- [x] [この](https://github.com/INxST/st-portfolio/issues/26#issuecomment-2258742358)指摘と被るかもだけど、スクロールでマウスストーカーが流れていっちゃうのが気になる！[こんな感じ](https://www.rakuten.design/)でマウスにずっと着いていてほしい
→横スクロールの時にはマウスストーカーが上に流れていっちゃうから直したい、、！
- [x] フッターのコンタクトをsvgに。ホバーした時の動きを線画に。[このサイト](https://www.eseagency.ch/en)のようにコンタクトホバーしたら次のコンタクトとかも同時にホバーの動きが出てほしい。（1単語だけじゃなくて）([issue](https://github.com/INxST/st-portfolio/issues/24#issuecomment-2290366702))
- [x]  月の部分、画像共有したので対応お願いします、！
- [x] ファーストビューの文字アニメーション、SP時のもの格納したので対応お願いします！
- [x] faviconも格納したので対応お願いします
- [x]  ロゴ部分、svgに変更ください
- [x]  sp時に実績のタイトル消えちゃってるので出してほしいです
- [x]  スマホ実機で見た時に、ブラウザ固定の下のバーの影響でそこに100vhで指定したいもの（添付のメニューとか、ページ遷移時のぼかしの範囲とか）がそこの位置に反映されてなくて、これってどうにかなったりするか確認してほしい、、！([issue](https://github.com/INxST/st-portfolio/issues/24#issuecomment-2295188756))

 ▼アバウト

- [x] 左右の余白全ページこれでお願いします！（ブラウザ幅375pxの段階で20近くくらいあってもいいかなあと思っている）
- [x] h1って現状コーディング上では、左右統一の20pxの余白がついているだけで、左が40px(20+20）になってないかなと思っているんだけどわいの環境があれなのかな？？制作一覧のh1も合わせて調整して欲しいです！[このサイト](https://yansukim.com/)みたいな感じ([issue](https://github.com/INxST/st-portfolio/issues/25#issuecomment-2290185081))

▼制作一覧

- [x] 各実績詳細への遷移カードについてる各カテゴリのタグのrow-gapを0.2remに
- [x] 実績詳細のタイトル30px→28pxに
- [x] h1サブテキストのmargin-leftを1→0.8remに([issue](https://github.com/INxST/st-portfolio/issues/26#issuecomment-2254108784))
- [x] tagは2行分領域確保。titleは1行であふれる分は三点リーダーで省略([issue](https://github.com/INxST/st-portfolio/issues/26#issuecomment-2291194117))
- [x] ヘッダーとスライダーの間のpaddingを削る（削った分スライダーのサイズも大きくする）([issue](https://github.com/INxST/st-portfolio/issues/26#issuecomment-2291194665))
- [x]   可能であれば、sp時に、縦スクロールだけじゃなくて横にスワイプで横に動くようにもしたいのですが、可能かな、、？→何ならsp時は普通に縦スクロールはできずに制作一覧は横スワイプだけでの動きでもいいです！([issue](https://github.com/INxST/st-portfolio/issues/26#issuecomment-2310291413))

> ▼制作詳細

- [x] 最初ページインした時、アニメーションをつけている影響かもだけど、MV部分は最初から表示されるようにしてほしい！！
- [x] 上記添付のタイトル部分だけどmax-width決めて改行される形がいいかなあ、、改行ない形だと画像の始まり部分がずれちゃうと思うので、一旦デザイン上だと640pxをmaxで作ってた！→ページ終わりの横渡りの部分も同様
- [x] h1のフォントウェイトを500にしてほしい
- [x] #177
- [x] #185

------------

○**優先度：中**
▼ローディングアニメーション
- [x] #142
ベタ塗りの色は、背景色に合わせる感じで（アバウトは黒、制作一覧詳細はベージュ）やるのが一番自然かなあと思っている。
- [x] #141 
  - 対応見送り  https://github.com/INxST/st-portfolio/issues/141#issuecomment-2564895711 

▼共有パーツ・トップページ
- [x] フッターの流れているコンタクトをクリックしたら
- [x] #143
- [x] #144
- [x] #145
- [x] #146
- [x] #147
- [x] #148
- [x]  上記可能そうであればヘッダーにも適用したい！（文字リストとmenuの文字）
- [x]  あと上記の話にも関係するんだけど、今見ているやつとそうでないやつ（添付で言うとmisiaの森が今見ていて、佐藤製麺所が見てないやつ）の色や不透明度を変えたくて、上記の指定次第だけど例えば添付だとmix-blend-mode:color-dodge; にしているんだけどこう言う感じのいけそうかな？（主のやつより目立たない感じにしたいからシンプルに不透明度下げるでもいい）
- [x]  worksのh2が内側によっている？？一応デザイン上だと、添付のところがイコールの想定だった
- [x] #149
- [x] #150
- [x] #151
- [x] #152
- [x] slackでもお伝えした、コンテンツ幅を可変にする件、お願いします！あと他にもpx指定あればご検討ください
- [x] #153

▼アバウト
- [x] #154
（pcは今の位置から大きくなるのでいいです！！([issue](https://github.com/INxST/st-portfolio/issues/25#issuecomment-2318261927))

▼制作一覧
- [x] #155
- [x] #156
→ただこれ見る環境によりまくってしまうのかなあ
- [x] spで見た時のブラウザ固定の下部バーの影響で画像のサイズが拡大縮小するのは良いんだけど、比率維持した状態で拡大縮小するようにしたいです、、！
- [x] #157
- [x] #158
- [x] #159
- [x] #178

▼制作詳細
- [x] #160
- [x] #161
- [x] #162
- [x] sp時のnext projectの横渡の画像をmv-sp（正方形のやつ）にして欲しいです！pc時は今のまま縦長の画像で良いです。
- [x] #163
- [x] #179
- [x] #180

----

○**優先度：低**
▼ローディングアニメーション

▼共有パーツ・トップページ
- [x] #183
pc時、下の余白を6px→5pに。
sp時、padding:4px, 12px, 3pxに。
- [x] #184
- [x] 細かいし出来たらで大丈夫！ローディング後にまたトップページ内ですぐにロゴを押してローディングした時に「TAIKI SATO」の文字アニメーションが起こらないからできればつけたい（他ページに行って戻ってきたり、トップページにずっといても一定の時間過ぎると再度通常にローディングアニメーションが起こる）
- [x]  トップのアバウト箇所のスピード感が全体的に少し早いので気持ちゆっくりしてほしいのと、画像同士のスピード感添付のようなイメージで調整いただければありがたいです！！（ちょっともしかしたらまたスピード調整していただくかも、、）([issue](https://github.com/INxST/st-portfolio/issues/24#issuecomment-2290366702))
- [x]  ワークス部分の切り替えをブラーとフェードインアウトで変更する要素のみ切り替え。（h2の部分や切り替えボタンはそのまま）切り替えボタンの部分ホバーで金文字に。

▼アバウト

▼制作一覧
- [x] #181

▼制作詳細
- [x] #182
→前LINEで話した[このサイト](https://www.snowpeak.co.jp/fieldsuitespa/hq/)くらいのパララックス
- [x] #207

**Comment by naoki-00-ito** [comment]
Safariかつ通信速度が遅いで再生ボタンが表示されてしまう件は下記のstyleを入れて様子見する

https://qiita.com/YukiYuki0508/items/651e70b50c278b16cfa1

**Comment by naoki-00-ito** [comment]
@taiki0521 

https://inxst.github.io/st-portfolio/

詳細のSafari崩れ以外は修正したのでご確認お願いします！

**Comment by taiki0521** [comment]
@naoki-00-ito 
ありがとう！！いい感じ！！！！

一点だけ、チェックボックス外させてもらったんだけど、
スクロールに応じてマウスストーカーが離れちゃう（上に流れていっちゃう）件に関して、よくなったんだけどやっぱりまだマウスストーカーが動きまくっちゃうから[楽天のサイト](https://www.rakuten.design/)くらいガッツりスクロール時はマウス自体にストーカーがくっ付いている感じにしたいんだけど厳しいかな？？

**Comment by naoki-00-ito** [comment]
実績詳細の横渡り画像のSP切り替えについて、
html構造も変なので合わせて修正する

```
a > picture > source, img
  > span...
```

のようなイメージ

https://github.com/INxST/st-portfolio/blob/main/src/components/NextWork.astro

**Comment by naoki-00-ito** [comment]
@taiki0521 
下記対応しました！
- #207 
- #148 
- #184 
- #183 
- #179 
- #182 
- #181

**Comment by naoki-00-ito** [comment]
@taiki0521 
対応完了したのでcloseします！
